name: oauth2
version: 1.0.0-dev
author: Dart Team <misc@dartlang.org>
homepage: http://github.com/dart-lang/oauth2
description: >
  A client library for authenticating with a remote service via OAuth2 on
  behalf of a user, and making authorized HTTP requests with the user's
  OAuth2 credentials.
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  http: '>=0.11.0 <0.12.0'
  http_parser: '>=0.0.0 <2.0.0'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
